services:
  app:
    # image: hectorrf16/finalprojectdo:latest
    image: finalprojectdo:app
    container_name: python-app
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ./app:/app
    ports:
    - 80:8080
    environment:
    - DEBUG=True
    - RELOADER=True

  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=hector
      - POSTGRES_PASSWORD=managerit
      - POSTGRES_DB=finalproject
      - TZ = Europe/Madrid
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    # image: dpage/pgadmin4:7
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=hectoor.16@icloud.com
      - PGADMIN_DEFAULT_PASSWORD=managerit
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Welcome back!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/pgadmin4
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    environment:
      - DATABASE_USER=hector
      - DATABASE_PASS=managerit
      - DATABASE_NAME=finalproject
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=managerit 
      - TZ=Europe/Madrid

volumes:
  postgres-db:
  pgadmin-data:
  grafana-data:
