services:
  app:
    build: .
    container_name: python-app
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - ./app:/app
    ports:
    - 80:8080
    environment:
    - DEBUG=True
    - RELOADER=True

  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    # command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      - POSTGRES_USER=hector
      - POSTGRES_PASSWORD=managerit
      - POSTGRES_DB=finalproject
      - TZ = Europe/Madrid
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./database/run.sh:/run.sh
      - ./database:/tmp
  
  pgadmin:
    # image: dpage/pgadmin4:7
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=hectoor.16@icloud.com
      - PGADMIN_DEFAULT_PASSWORD=managerit
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_LOGIN_BANNER="Welcome back!"
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/pgadmin4
      - ./database/servers.json:/pgadmin4/servers.json
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    depends_on:
      - db
    ports: 
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/provisioning/datasources/dashboards:/dashboards
      - ./database/:/home/tmp
    environment:
      - DATABASE_USER=hector
      - DATABASE_PASS=managerit
      - DATABASE_NAME=finalproject
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=managerit 
      - TZ=Europe/Madrid

volumes:
  postgres-db:
  pgadmin-data:
  grafana-data:
