datasources:
- name: db
  type: postgres
  url: $DATABASE_HOST:$DATABASE_PORT
  user: $DATABASE_USER
  database: $DATABASE_NAME
  password: managerit
  access: proxy
  basicAuth: false
  withCredentials: false
  isDefault: true
  secureJsonData:
    password: $DATABASE_PASS
  jsonData:
    postgresVersion: 1000
    sslmode: disable
  version: 1
  editable: true