apiVersion: 1

datasources:
- name: db
  type: postgres
  url: db:5432
  user: hector
  database: finalproject
  password: ""
  access: proxy
  basicAuth: false
  uid: "P7BDC25D1694EF984"
  withCredentials: false
  isDefault: true
  jsonData:
    postgresVersion: 1000
    sslmode: disable
    # tlsAuth: true
    # tlsAuthWithCACert: true
    # tlsSkipVerify: true
  secureJsonData:
    password: managerit
    # tlsCACert: $__file{/tmp/server.csr}
    # tlsClientCert: $__file{/tmp/server.crt}
    # tlsClientkey: $__file{/tmp/server.key}
  version: 1
  editable: true