name: FinalProjectDO Workflow
run-name: Testing workflow with GitHub Actions
on:
  pull_request:
    branches:
      - main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job automatically triggered by ${{github.event_name}} event."
      - name: check out repository code
        uses: actions/checkout@v3
      - name: init app deployment
        run: bash ./run.sh 0
      - name: checking docker run
        run: docker ps --format '{{.Names}}\t{{.Status}}' | awk -F '\t' '{print $2}'
      - name: testing dockers repair
        run: bash ./run.sh 2 8  
      - name: checking docker run after repair
        run: docker ps --format '{{.Names}}\t{{.Status}}' | awk -F '\t' '{print $2}'
      - name: testing docker uninstall
        run: bash ./run.sh 3